/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vista;

import controlador.Controlador;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Categoria;
import modelo.ListCat;
import modelo.ListaProd;
import modelo.ListaUsu;
import modelo.Producto;
import modelo.ProductoC;
import modelo.ProductosComanda;
import modelo.Usuario;
/**
 *
 * @author ruben
 */
public class GestionWindow extends javax.swing.JFrame {
    Controlador c;
    public int idCom;
    public String empleado;
    
    /** Creates new form GestionWindow */
    public GestionWindow() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public GestionWindow(Controlador c) {
        initComponents();
        setLocationRelativeTo(null);
        this.c = c;
        
        b1.setText("1");
        b2.setText("2");
        b3.setText("3");
        b4.setText("4");
        b5.setText("5");
        b6.setText("6");
        b7.setText("7");
        b8.setText("8");
        b9.setText("9");
        b10.setText("10");
        b11.setText("11");
        b12.setText("12");
        b13.setText("13");
        b14.setText("14");
        b15.setText("15");
        b16.setText("16");
        b17.setText("17");
        b18.setText("18");
        b19.setText("19");
        b20.setText("20");
    }
    
    public void DisminuirMesas(){
                b1.setText(Integer.parseInt(b1.getText()) - 20 + "");
                b2.setText(Integer.parseInt(b2.getText()) - 20 + "");
                b3.setText(Integer.parseInt(b3.getText()) - 20 + "");
                b4.setText(Integer.parseInt(b4.getText()) - 20 + "");
                b5.setText(Integer.parseInt(b5.getText()) - 20 + "");
                b6.setText(Integer.parseInt(b6.getText()) - 20 + "");
                b7.setText(Integer.parseInt(b7.getText()) - 20 + "");
                b8.setText(Integer.parseInt(b8.getText()) - 20 + "");
                b9.setText(Integer.parseInt(b9.getText()) - 20 + "");
                b10.setText(Integer.parseInt(b10.getText()) - 20 + "");
                b11.setText(Integer.parseInt(b11.getText()) - 20 + "");
                b12.setText(Integer.parseInt(b12.getText()) - 20 + "");
                b13.setText(Integer.parseInt(b13.getText()) - 20 + "");
                b14.setText(Integer.parseInt(b14.getText()) - 20 + "");
                b15.setText(Integer.parseInt(b15.getText()) - 20 + "");
                b16.setText(Integer.parseInt(b16.getText()) - 20 + "");
                b17.setText(Integer.parseInt(b17.getText()) - 20 + "");
                b18.setText(Integer.parseInt(b18.getText()) - 20 + "");
                b19.setText(Integer.parseInt(b19.getText()) - 20 + "");
                b20.setText(Integer.parseInt(b20.getText()) - 20 + "");
             
            
        
        
    }
    
    public void AumentarMesas(){
        
            b1.setText(Integer.parseInt(b1.getText()) + 20 + "");
            b2.setText(Integer.parseInt(b2.getText()) + 20 + "");
            b3.setText(Integer.parseInt(b3.getText()) + 20 + "");
            b4.setText(Integer.parseInt(b4.getText()) + 20 + "");
            b5.setText(Integer.parseInt(b5.getText()) + 20 + "");
            b6.setText(Integer.parseInt(b6.getText()) + 20 + "");
            b7.setText(Integer.parseInt(b7.getText()) + 20 + "");
            b8.setText(Integer.parseInt(b8.getText()) + 20 + "");
            b9.setText(Integer.parseInt(b9.getText()) + 20 + "");
            b10.setText(Integer.parseInt(b10.getText()) + 20 + "");
            b11.setText(Integer.parseInt(b11.getText()) + 20 + "");
            b12.setText(Integer.parseInt(b12.getText()) + 20 + "");
            b13.setText(Integer.parseInt(b13.getText()) + 20 + "");
            b14.setText(Integer.parseInt(b14.getText()) + 20 + "");
            b15.setText(Integer.parseInt(b15.getText()) + 20 + "");
            b16.setText(Integer.parseInt(b16.getText()) + 20 + "");
            b17.setText(Integer.parseInt(b17.getText()) + 20 + "");
            b18.setText(Integer.parseInt(b18.getText()) + 20 + "");
            b19.setText(Integer.parseInt(b19.getText()) + 20 + "");
            b20.setText(Integer.parseInt(b20.getText()) + 20 + "");
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ventanas = new javax.swing.JTabbedPane();
        panelComandas = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        b10 = new javax.swing.JButton();
        bDisminuir = new javax.swing.JButton();
        bAumentar = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        b11 = new javax.swing.JButton();
        b12 = new javax.swing.JButton();
        b13 = new javax.swing.JButton();
        b14 = new javax.swing.JButton();
        b15 = new javax.swing.JButton();
        b16 = new javax.swing.JButton();
        b17 = new javax.swing.JButton();
        b18 = new javax.swing.JButton();
        b19 = new javax.swing.JButton();
        b20 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListCategorias = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        comanda = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        lblComanda = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        listProd = new javax.swing.JList<>();
        bInsertarProdC = new javax.swing.JButton();
        bQuitarProdC = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtInfoProd = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        LblMesa = new javax.swing.JLabel();
        bElegirMesa = new javax.swing.JButton();
        bIniciar = new javax.swing.JButton();
        bPagar = new javax.swing.JButton();
        cbEmpleado = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        panelProductos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TxtCodCat = new javax.swing.JTextField();
        TxtNomCat = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaGCat = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        tProd = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        TxtNomProd = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TxtCodProd = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        CbCategorias = new javax.swing.JComboBox<>();
        TxtPrecio = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        InfoProd = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        BInsProd = new javax.swing.JButton();
        BelimProd = new javax.swing.JButton();
        BactProd = new javax.swing.JButton();
        BactCat = new javax.swing.JButton();
        BinsCat = new javax.swing.JButton();
        BelimCat = new javax.swing.JButton();
        panelGestionUsu = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        tUsu = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtUsu = new javax.swing.JTextField();
        txtNomUsu = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        bActUsu = new javax.swing.JButton();
        bEdUsu = new javax.swing.JButton();
        bBorUsu = new javax.swing.JButton();
        bInsUsu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        b1.setText("11");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        b2.setText("12");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        b3.setText("13");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        b4.setText("14");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        b5.setText("15");
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });

        b6.setText("16");
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });

        b7.setText("17");
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });

        b8.setText("18");
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });

        b9.setText("19");
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });

        b10.setText("20");
        b10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(b1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b10)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b1)
                    .addComponent(b2)
                    .addComponent(b3)
                    .addComponent(b4)
                    .addComponent(b5)
                    .addComponent(b6)
                    .addComponent(b7)
                    .addComponent(b8)
                    .addComponent(b9)
                    .addComponent(b10))
                .addContainerGap())
        );

        bDisminuir.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        bDisminuir.setText("<");
        bDisminuir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDisminuirActionPerformed(evt);
            }
        });

        bAumentar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        bAumentar.setText(">");
        bAumentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAumentarActionPerformed(evt);
            }
        });

        b11.setText("11");
        b11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b11ActionPerformed(evt);
            }
        });

        b12.setText("12");
        b12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b12ActionPerformed(evt);
            }
        });

        b13.setText("13");
        b13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b13ActionPerformed(evt);
            }
        });

        b14.setText("14");
        b14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b14ActionPerformed(evt);
            }
        });

        b15.setText("15");
        b15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b15ActionPerformed(evt);
            }
        });

        b16.setText("16");
        b16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b16ActionPerformed(evt);
            }
        });

        b17.setText("17");
        b17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b17ActionPerformed(evt);
            }
        });

        b18.setText("18");
        b18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b18ActionPerformed(evt);
            }
        });

        b19.setText("19");
        b19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b19ActionPerformed(evt);
            }
        });

        b20.setText("20");
        b20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b20ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(b11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b20)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b11)
                    .addComponent(b12)
                    .addComponent(b13)
                    .addComponent(b14)
                    .addComponent(b15)
                    .addComponent(b16)
                    .addComponent(b17)
                    .addComponent(b18)
                    .addComponent(b19)
                    .addComponent(b20))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bDisminuir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bAumentar)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bDisminuir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bAumentar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        ListCategorias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListCategoriasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ListCategorias);

        jLabel3.setText("Categorias");

        comanda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id Producto", "Nombre Producto", "Precio"
            }
        ));
        jScrollPane5.setViewportView(comanda);

        jLabel4.setText("Productos");

        lblComanda.setText("Comanda");

        listProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listProdMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(listProd);

        bInsertarProdC.setText(">");
        bInsertarProdC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInsertarProdCActionPerformed(evt);
            }
        });

        bQuitarProdC.setText("<");
        bQuitarProdC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bQuitarProdCActionPerformed(evt);
            }
        });

        txtInfoProd.setColumns(20);
        txtInfoProd.setRows(5);
        txtInfoProd.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtInfoProd.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtInfoProd.setEnabled(false);
        jScrollPane4.setViewportView(txtInfoProd);

        jLabel11.setText("Info");

        LblMesa.setText("Mesa: ");

        bElegirMesa.setText("Elegir mesas");
        bElegirMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bElegirMesaActionPerformed(evt);
            }
        });

        bIniciar.setText("Iniciar Comanda");
        bIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIniciarActionPerformed(evt);
            }
        });

        bPagar.setText("Pagar");
        bPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPagarActionPerformed(evt);
            }
        });

        jLabel12.setText("Empleado:");

        javax.swing.GroupLayout panelComandasLayout = new javax.swing.GroupLayout(panelComandas);
        panelComandas.setLayout(panelComandasLayout);
        panelComandasLayout.setHorizontalGroup(
            panelComandasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelComandasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelComandasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelComandasLayout.createSequentialGroup()
                        .addGroup(panelComandasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelComandasLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel11))
                            .addGroup(panelComandasLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(panelComandasLayout.createSequentialGroup()
                                .addComponent(bElegirMesa)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(panelComandasLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelComandasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelComandasLayout.createSequentialGroup()
                                .addGroup(panelComandasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                                    .addComponent(jScrollPane7))
                                .addGap(18, 18, 18)
                                .addGroup(panelComandasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bInsertarProdC, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bQuitarProdC, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(panelComandasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelComandasLayout.createSequentialGroup()
                                        .addComponent(lblComanda)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(LblMesa)
                                        .addGap(87, 87, 87))))
                            .addGroup(panelComandasLayout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(panelComandasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bIniciar, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panelComandasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bPagar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbEmpleado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())
                    .addGroup(panelComandasLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panelComandasLayout.setVerticalGroup(
            panelComandasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelComandasLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelComandasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelComandasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelComandasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(LblMesa, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblComanda)))
                .addGroup(panelComandasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelComandasLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panelComandasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane7)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(panelComandasLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(bInsertarProdC)
                        .addGap(18, 18, 18)
                        .addComponent(bQuitarProdC)))
                .addGap(18, 18, 18)
                .addGroup(panelComandasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelComandasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(panelComandasLayout.createSequentialGroup()
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(58, 58, 58))
                        .addGroup(panelComandasLayout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bElegirMesa)
                            .addGap(54, 54, 54)))
                    .addGroup(panelComandasLayout.createSequentialGroup()
                        .addGroup(panelComandasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelComandasLayout.createSequentialGroup()
                                .addComponent(bPagar)
                                .addGap(18, 18, 18)
                                .addGroup(panelComandasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12)))
                            .addComponent(bIniciar))
                        .addGap(36, 36, 36))))
        );

        ventanas.addTab("Comandas", panelComandas);

        jLabel1.setText("Categoría");

        jLabel2.setText("Codigo");

        jScrollPane2.setViewportView(listaGCat);

        tProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Categoria", "Info", "Precio"
            }
        ));
        jScrollPane3.setViewportView(tProd);

        jLabel6.setText("Nombre");

        jLabel7.setText("Codigo");

        jLabel8.setText("Categoria");

        jLabel9.setText("Precio");

        InfoProd.setColumns(20);
        InfoProd.setRows(5);
        jScrollPane6.setViewportView(InfoProd);

        jLabel10.setText("Info");

        BInsProd.setText("Insertar Producto");
        BInsProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BInsProdActionPerformed(evt);
            }
        });

        BelimProd.setText("Eliminar Producto");
        BelimProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BelimProdActionPerformed(evt);
            }
        });

        BactProd.setText("Actualizar Producto");
        BactProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BactProdActionPerformed(evt);
            }
        });

        BactCat.setText("Actualizar Cat");
        BactCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BactCatActionPerformed(evt);
            }
        });

        BinsCat.setText("Insertar Cat");
        BinsCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BinsCatActionPerformed(evt);
            }
        });

        BelimCat.setText("Eliminar Cat");
        BelimCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BelimCatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelProductosLayout = new javax.swing.GroupLayout(panelProductos);
        panelProductos.setLayout(panelProductosLayout);
        panelProductosLayout.setHorizontalGroup(
            panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProductosLayout.createSequentialGroup()
                .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelProductosLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelProductosLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtCodCat, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelProductosLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtNomCat, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProductosLayout.createSequentialGroup()
                        .addContainerGap(33, Short.MAX_VALUE)
                        .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2)
                            .addGroup(panelProductosLayout.createSequentialGroup()
                                .addComponent(BactCat)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BelimCat)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BinsCat)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelProductosLayout.createSequentialGroup()
                        .addComponent(jScrollPane3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelProductosLayout.createSequentialGroup()
                        .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelProductosLayout.createSequentialGroup()
                                .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(panelProductosLayout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TxtNomProd, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(panelProductosLayout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(TxtCodProd, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel8)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TxtPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(CbCategorias, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProductosLayout.createSequentialGroup()
                                .addComponent(BactProd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BelimProd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BInsProd)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(45, Short.MAX_VALUE))))
        );
        panelProductosLayout.setVerticalGroup(
            panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProductosLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelProductosLayout.createSequentialGroup()
                        .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(TxtCodCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(TxtCodProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(CbCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(TxtNomCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(TxtNomProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(TxtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(BInsProd)
                                .addComponent(BelimProd)
                                .addComponent(BactProd))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(BinsCat)
                                .addComponent(BelimCat)
                                .addComponent(BactCat)))
                        .addGap(18, 18, 18))
                    .addGroup(panelProductosLayout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)))
                .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(115, Short.MAX_VALUE))
        );

        ventanas.addTab("Gestion Productos", panelProductos);

        tUsu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "usuario", "nombre", "password"
            }
        ));
        jScrollPane9.setViewportView(tUsu);

        jLabel13.setText("Usuario:");

        jLabel14.setText("Nombre:");

        jLabel15.setText("Password");

        bActUsu.setText("Actualizar usuaros");
        bActUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActUsuActionPerformed(evt);
            }
        });

        bEdUsu.setText("Nuevo Usuario");
        bEdUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEdUsuActionPerformed(evt);
            }
        });

        bBorUsu.setText("Borrar usuario");
        bBorUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBorUsuActionPerformed(evt);
            }
        });

        bInsUsu.setText("Insertar Usuario");
        bInsUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInsUsuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGestionUsuLayout = new javax.swing.GroupLayout(panelGestionUsu);
        panelGestionUsu.setLayout(panelGestionUsuLayout);
        panelGestionUsuLayout.setHorizontalGroup(
            panelGestionUsuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGestionUsuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGestionUsuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane9)
                    .addGroup(panelGestionUsuLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelGestionUsuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelGestionUsuLayout.createSequentialGroup()
                                .addComponent(txtUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNomUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 45, Short.MAX_VALUE))
                            .addGroup(panelGestionUsuLayout.createSequentialGroup()
                                .addComponent(bActUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bEdUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bBorUsu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(bInsUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        panelGestionUsuLayout.setVerticalGroup(
            panelGestionUsuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGestionUsuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGestionUsuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(txtNomUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(panelGestionUsuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bActUsu)
                    .addComponent(bEdUsu)
                    .addComponent(bBorUsu)
                    .addComponent(bInsUsu))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        ventanas.addTab("Gestor Usu / Empleados", panelGestionUsu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ventanas)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ventanas)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BelimCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BelimCatActionPerformed
        try {
            Categoria cat = new Categoria();
            cat.nom = listaGCat.getSelectedValue();
            DefaultListModel dfm = new DefaultListModel();
            ListCat lc = c.EliminarCategoria(cat);
            for (var ca : lc.categorias){
                dfm.addElement(ca.nom);
                CbCategorias.addItem(ca.nom);
            }

            ListCategorias.setModel(dfm);
            listaGCat.setModel(dfm);
        } catch (SQLException ex) {
            Logger.getLogger(GestionWindow.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_BelimCatActionPerformed

    private void BinsCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BinsCatActionPerformed
        Categoria cat = new Categoria(TxtCodCat.getText(), TxtNomCat.getText());
        try {
            ListCat lc = c.InsertarCategoria(cat);
            DefaultListModel dfm = new DefaultListModel();
            CbCategorias.removeAllItems();
            for (var ca : lc.categorias){
                dfm.addElement(ca.getNom());

                CbCategorias.addItem(ca.nom);
            }

            ListCategorias.setModel(dfm);
            listaGCat.setModel(dfm);
        } catch (SQLException ex) {
            Logger.getLogger(GestionWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BinsCatActionPerformed

    private void BactCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BactCatActionPerformed
        try {
            DefaultListModel dfm = new DefaultListModel();
            ListCat lc = c.ActualizarCategorias();
            CbCategorias.removeAllItems();
            for (var ca : lc.categorias){
                dfm.addElement(ca.nom);
                CbCategorias.addItem(ca.nom);
            }
            ListCategorias.setModel(dfm);
            listaGCat.setModel(dfm);
        } catch (SQLException ex) {
            Logger.getLogger(GestionWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BactCatActionPerformed

    private void BactProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BactProdActionPerformed
        try{
            ListaProd lp = c.ActualizarProductos();
            DefaultTableModel dfm = new DefaultTableModel();

            dfm.addColumn("id");
            dfm.addColumn("nombre");
            dfm.addColumn("categoria");
            dfm.addColumn("info");
            dfm.addColumn("precio");
            for (var ca : lp.lp){
                dfm.addRow(new Object[] {ca.getId(), ca.getNombre(), ca.getCategoria(), ca.getInfo(), ca.getPrecio()});
            }
            tProd.setModel(dfm);
        } catch (SQLException ex) {
            Logger.getLogger(GestionWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BactProdActionPerformed

    private void BInsProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BInsProdActionPerformed
        try {
            Producto p = new Producto(TxtCodProd.getText(), TxtNomProd.getText(), CbCategorias.getSelectedItem().toString(), Double.parseDouble(TxtPrecio.getText()), InfoProd.getText());
            ListaProd lc = c.InsertarProducto(p);
            DefaultTableModel dfm = new DefaultTableModel();

            dfm.addColumn("id");
            dfm.addColumn("nombre");
            dfm.addColumn("categoria");
            dfm.addColumn("info");
            dfm.addColumn("precio");
            for (var ca : lc.lp){
                dfm.addRow(new Object[] {ca.getId(), ca.getNombre(), ca.getCategoria(), ca.getInfo(), ca.getPrecio()});
            }
            tProd.setModel(dfm);
        } catch (SQLException ex) {
            Logger.getLogger(GestionWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BInsProdActionPerformed

    private void bIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIniciarActionPerformed
        try {
            if (c.ComprobarComanda().longitud() == 0){
                c.CrearComanda(cbEmpleado.getSelectedItem().toString());
            }
        } catch (SQLException ex) {
            Logger.getLogger(GestionWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bIniciarActionPerformed

    private void bElegirMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bElegirMesaActionPerformed
        try {
            String i = JOptionPane.showInputDialog("Introduce cuantas mesas tiene el bar");
            c.CrearMesas(Integer.parseInt(i));
        } catch (SQLException ex) {
            Logger.getLogger(GestionWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bElegirMesaActionPerformed

    private void bQuitarProdCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bQuitarProdCActionPerformed
        try {
            int row;
            if ((row = comanda.getSelectedRow()) != -1){
                ProductoC p = new ProductoC(comanda.getValueAt(row, 0).toString(), comanda.getValueAt(row, 1).toString(), Double.parseDouble(comanda.getValueAt(row, 2).toString()));
                ProductosComanda pc = c.eliminarDeComanda(p);
                RellenarComanda(pc);
            }
        } catch (SQLException ex) {
            Logger.getLogger(GestionWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bQuitarProdCActionPerformed

    private void bInsertarProdCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInsertarProdCActionPerformed
        try{
            if (listProd.getSelectedIndex() != -1){
                String nombre = listProd.getSelectedValue();
                ListaProd lp = c.productos;
                ProductosComanda pc = new ProductosComanda();
                for (var p : lp.lp){
                    if (p.getNombre().equals(nombre)){
                        pc = c.InsertarEnComanda(p);
                    }
                }
                RellenarComanda(pc);
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_bInsertarProdCActionPerformed

    private void listProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listProdMouseClicked
        String nombre = listProd.getSelectedValue();
        ListaProd lp = c.productos;
        for (var p : lp.lp){
            if (nombre.equals(p.getNombre()))
            txtInfoProd.setText(p.getInfo());
        }
    }//GEN-LAST:event_listProdMouseClicked

    private void ListCategoriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListCategoriasMouseClicked
        try {
            String nombre = ListCategorias.getSelectedValue();
            ListaProd lp = c.ActualizarProductos();
            
            DefaultListModel dfm = new DefaultListModel();
            for (var p : lp.lp){
                if (p.getCategoria().equals(nombre)){
                    dfm.addElement(p.getNombre());
                }
            }
            listProd.setModel(dfm);
        } catch (SQLException ex) {
            Logger.getLogger(GestionWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ListCategoriasMouseClicked

    private void b20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b20ActionPerformed
        c.idMesa = Integer.parseInt(b20.getText());
        try {
            LblMesa.setText("Mesa: " + b20.getText());
            ProductosComanda pc = c.ComprobarComanda();
            RellenarComanda(pc);
        } catch (SQLException ex) {
            Logger.getLogger(GestionWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_b20ActionPerformed

    private void b19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b19ActionPerformed
        c.idMesa = Integer.parseInt(b19.getText());
        try {
            LblMesa.setText("Mesa: " + b19.getText());
            ProductosComanda pc = c.ComprobarComanda();
            RellenarComanda(pc);
        } catch (SQLException ex) {
            Logger.getLogger(GestionWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_b19ActionPerformed

    private void b18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b18ActionPerformed
        c.idMesa = Integer.parseInt(b18.getText());
        try {
            LblMesa.setText("Mesa: " + b18.getText());
            ProductosComanda pc = c.ComprobarComanda();
            RellenarComanda(pc);
        } catch (SQLException ex) {
            Logger.getLogger(GestionWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_b18ActionPerformed

    private void b17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b17ActionPerformed
        c.idMesa = Integer.parseInt(b17.getText());
        try {
            LblMesa.setText("Mesa: " + b17.getText());
            ProductosComanda pc = c.ComprobarComanda();
            RellenarComanda(pc);
        } catch (SQLException ex) {
            Logger.getLogger(GestionWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_b17ActionPerformed

    private void b16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b16ActionPerformed
        c.idMesa = Integer.parseInt(b16.getText());
        try {
            LblMesa.setText("Mesa: " + b16.getText());
            ProductosComanda pc = c.ComprobarComanda();
            RellenarComanda(pc);
        } catch (SQLException ex) {
            Logger.getLogger(GestionWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_b16ActionPerformed

    private void b15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b15ActionPerformed
        c.idMesa = Integer.parseInt(b15.getText());
        try {
            LblMesa.setText("Mesa: " + b15.getText());
            ProductosComanda pc = c.ComprobarComanda();
            RellenarComanda(pc);
        } catch (SQLException ex) {
            Logger.getLogger(GestionWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_b15ActionPerformed

    private void b14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b14ActionPerformed
        c.idMesa = Integer.parseInt(b14.getText());
        try {
            LblMesa.setText("Mesa: " + b14.getText());
            ProductosComanda pc = c.ComprobarComanda();
            RellenarComanda(pc);
        } catch (SQLException ex) {
            Logger.getLogger(GestionWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_b14ActionPerformed

    private void b13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b13ActionPerformed
        c.idMesa = Integer.parseInt(b13.getText());

        try {
            LblMesa.setText("Mesa: " + b13.getText());
            ProductosComanda pc = c.ComprobarComanda();
            RellenarComanda(pc);
        } catch (SQLException ex) {
            Logger.getLogger(GestionWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_b13ActionPerformed

    private void b12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b12ActionPerformed
        c.idMesa = Integer.parseInt(b12.getText());
        try {
            LblMesa.setText("Mesa: " + b12.getText());
            ProductosComanda pc = c.ComprobarComanda();
            RellenarComanda(pc);
        } catch (SQLException ex) {
            Logger.getLogger(GestionWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_b12ActionPerformed

    private void b11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b11ActionPerformed
        c.idMesa = Integer.parseInt(b11.getText());
        try {
            LblMesa.setText("Mesa: " + b11.getText());
            ProductosComanda pc = c.ComprobarComanda();
            RellenarComanda(pc);
        } catch (SQLException ex) {
            Logger.getLogger(GestionWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_b11ActionPerformed

    private void bAumentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAumentarActionPerformed

        if (!((Integer.parseInt(b1.getText()) + 20) >= c.cantidadMesas)){
            AumentarMesas();
        }

        if ((Integer.parseInt(b2.getText()) > c.cantidadMesas)){
            b2.setVisible(false);
        }else{
            b2.setVisible(true);
        }

        if ((Integer.parseInt(b3.getText()) > c.cantidadMesas)){
            b3.setVisible(false);
        }else{
            b3.setVisible(true);
        }

        if ((Integer.parseInt(b4.getText()) > c.cantidadMesas)){
            b4.setVisible(false);
        }else{
            b4.setVisible(true);
        }

        if ((Integer.parseInt(b5.getText()) > c.cantidadMesas)){
            b5.setVisible(false);
        }else{
            b5.setVisible(true);
        }

        if ((Integer.parseInt(b6.getText()) > c.cantidadMesas)){
            b6.setVisible(false);
        }else{
            b6.setVisible(true);
        }

        if ((Integer.parseInt(b7.getText()) > c.cantidadMesas)){
            b7.setVisible(false);
        }else{
            b7.setVisible(true);
        }

        if ((Integer.parseInt(b8.getText()) > c.cantidadMesas)){
            b8.setVisible(false);
        }else{
            b8.setVisible(true);
        }

        if ((Integer.parseInt(b9.getText()) > c.cantidadMesas)){
            b9.setVisible(false);
        }else{
            b9.setVisible(true);
        }

        if ((Integer.parseInt(b10.getText()) > c.cantidadMesas)){
            b10.setVisible(false);
        }else{
            b10.setVisible(true);
        }

        if ((Integer.parseInt(b11.getText()) > c.cantidadMesas)){
            b11.setVisible(false);
        }else{
            b11.setVisible(true);
        }

        if ((Integer.parseInt(b12.getText()) > c.cantidadMesas)){
            b12.setVisible(false);
        }else{
            b12.setVisible(true);
        }

        if ((Integer.parseInt(b13.getText()) > c.cantidadMesas)){
            b13.setVisible(false);
        }else{
            b13.setVisible(true);
        }

        if ((Integer.parseInt(b14.getText()) > c.cantidadMesas)){
            b14.setVisible(false);
        }else{
            b14.setVisible(true);
        }

        if ((Integer.parseInt(b15.getText()) > c.cantidadMesas)){
            b15.setVisible(false);
        }else{
            b15.setVisible(true);
        }

        if ((Integer.parseInt(b16.getText()) > c.cantidadMesas)){
            b16.setVisible(false);
        }else{
            b16.setVisible(true);
        }

        if ((Integer.parseInt(b17.getText()) > c.cantidadMesas)){
            b17.setVisible(false);
        }else{
            b17.setVisible(true);
        }

        if ((Integer.parseInt(b18.getText()) > c.cantidadMesas)){
            b18.setVisible(false);
        }else{
            b18.setVisible(true);
        }

        if ((Integer.parseInt(b19.getText()) > c.cantidadMesas)){
            b19.setVisible(false);
        }else{
            b19.setVisible(true);
        }

        if ((Integer.parseInt(b20.getText()) > c.cantidadMesas)){
            b20.setVisible(false);
        }else{
            b20.setVisible(true);
        }
    }//GEN-LAST:event_bAumentarActionPerformed

    private void bDisminuirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDisminuirActionPerformed
        if (((Integer.parseInt(b1.getText()) - 20) < c.cantidadMesas) && (Integer.parseInt(b1.getText()) - 20) > 0){
            DisminuirMesas();
        }

        if ((Integer.parseInt(b2.getText()) <= c.cantidadMesas)){
            b2.setVisible(true);
        }else{
            b2.setVisible(false);
        }

        if ((Integer.parseInt(b3.getText()) <= c.cantidadMesas)){
            b3.setVisible(true);
        }else{
            b3.setVisible(false);
        }

        if ((Integer.parseInt(b4.getText()) <= c.cantidadMesas)){
            b4.setVisible(true);
        }else{
            b4.setVisible(false);
        }

        if ((Integer.parseInt(b5.getText()) <= c.cantidadMesas)){
            b5.setVisible(true);
        }else{
            b5.setVisible(false);
        }

        if ((Integer.parseInt(b6.getText()) <= c.cantidadMesas)){
            b6.setVisible(true);
        }else{
            b6.setVisible(false);
        }

        if ((Integer.parseInt(b7.getText()) <= c.cantidadMesas)){
            b7.setVisible(true);
        }else{
            b7.setVisible(false);
        }

        if ((Integer.parseInt(b8.getText()) <= c.cantidadMesas)){
            b8.setVisible(true);
        }else{
            b8.setVisible(false);
        }

        if ((Integer.parseInt(b9.getText()) <= c.cantidadMesas)){
            b9.setVisible(true);
        }else{
            b9.setVisible(false);
        }

        if ((Integer.parseInt(b10.getText()) <= c.cantidadMesas)){
            b10.setVisible(true);
        }else{
            b10.setVisible(false);
        }

        if ((Integer.parseInt(b11.getText()) <= c.cantidadMesas)){
            b11.setVisible(true);
        }else{
            b11.setVisible(false);
        }

        if ((Integer.parseInt(b12.getText()) <= c.cantidadMesas)){
            b12.setVisible(true);
        }else{
            b12.setVisible(false);
        }

        if ((Integer.parseInt(b13.getText()) <= c.cantidadMesas)){
            b13.setVisible(true);
        }else{
            b13.setVisible(false);
        }

        if ((Integer.parseInt(b14.getText()) <= c.cantidadMesas)){
            b14.setVisible(true);
        }else{
            b14.setVisible(false);
        }

        if ((Integer.parseInt(b15.getText()) <= c.cantidadMesas)){
            b15.setVisible(true);
        }else{
            b15.setVisible(false);
        }

        if ((Integer.parseInt(b16.getText()) <= c.cantidadMesas)){
            b16.setVisible(true);
        }else{
            b16.setVisible(false);
        }

        if ((Integer.parseInt(b17.getText()) <= c.cantidadMesas)){
            b17.setVisible(true);
        }else{
            b17.setVisible(false);
        }

        if ((Integer.parseInt(b18.getText()) <= c.cantidadMesas)){
            b18.setVisible(true);
        }else{
            b18.setVisible(false);
        }

        if ((Integer.parseInt(b19.getText()) <= c.cantidadMesas)){
            b19.setVisible(true);
        }else{
            b19.setVisible(false);
        }

        if ((Integer.parseInt(b20.getText()) <= c.cantidadMesas)){
            b20.setVisible(true);
        }else{
            b20.setVisible(false);
        }
    }//GEN-LAST:event_bDisminuirActionPerformed

    private void b10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b10ActionPerformed
        c.idMesa = Integer.parseInt(b10.getText());

        try {
            LblMesa.setText("Mesa: " + b10.getText());
            ProductosComanda pc = c.ComprobarComanda();
            RellenarComanda(pc);
        } catch (SQLException ex) {
            Logger.getLogger(GestionWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_b10ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
        c.idMesa = Integer.parseInt(b9.getText());
        try {
            LblMesa.setText("Mesa: " + b9.getText());
            ProductosComanda pc = c.ComprobarComanda();
            RellenarComanda(pc);
        } catch (SQLException ex) {
            Logger.getLogger(GestionWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_b9ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        c.idMesa = Integer.parseInt(b8.getText());
        try {
            LblMesa.setText("Mesa: " + b8.getText());
            ProductosComanda pc = c.ComprobarComanda();
            RellenarComanda(pc);
        } catch (SQLException ex) {
            Logger.getLogger(GestionWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_b8ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        c.idMesa = Integer.parseInt(b7.getText());
        try {
            LblMesa.setText("Mesa: " + b7.getText());
            ProductosComanda pc = c.ComprobarComanda();
            RellenarComanda(pc);
        } catch (SQLException ex) {
            Logger.getLogger(GestionWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_b7ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        c.idMesa = Integer.parseInt(b6.getText());
        try {
            LblMesa.setText("Mesa: " + b6.getText());
            ProductosComanda pc = c.ComprobarComanda();
            RellenarComanda(pc);
        } catch (SQLException ex) {
            Logger.getLogger(GestionWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_b6ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        c.idMesa = Integer.parseInt(b5.getText());
        try {
            LblMesa.setText("Mesa: " + b5.getText());
            ProductosComanda pc = c.ComprobarComanda();
            RellenarComanda(pc);
        } catch (SQLException ex) {
            Logger.getLogger(GestionWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_b5ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        c.idMesa = Integer.parseInt(b4.getText());
        try {
            LblMesa.setText("Mesa: " + b4.getText());
            ProductosComanda pc = c.ComprobarComanda();
            RellenarComanda(pc);
        } catch (SQLException ex) {
            Logger.getLogger(GestionWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_b4ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        c.idMesa = Integer.parseInt(b3.getText());
        try {
            LblMesa.setText("Mesa: " + b3.getText());
            ProductosComanda pc = c.ComprobarComanda();
            RellenarComanda(pc);
        } catch (SQLException ex) {
            Logger.getLogger(GestionWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_b3ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        c.idMesa = Integer.parseInt(b2.getText());
        try {
            LblMesa.setText("Mesa: " + b2.getText());
            ProductosComanda pc = c.ComprobarComanda();
            RellenarComanda(pc);
        } catch (SQLException ex) {
            Logger.getLogger(GestionWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_b2ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        c.idMesa = Integer.parseInt(b1.getText());
        try {
            LblMesa.setText("Mesa: " + b1.getText());
            ProductosComanda pc = c.ComprobarComanda();
            RellenarComanda(pc);
        } catch (SQLException ex) {
            Logger.getLogger(GestionWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_b1ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        try {
            DefaultListModel dfm = new DefaultListModel();
            ListCat lc = c.ActualizarCategorias();
            ListaUsu lu = c.ActualizarUsuario();
            cbEmpleado.removeAllItems();
            
            for (var e : lu.usuarios){
                cbEmpleado.addItem(e.getNombre());
            }
            
            c.ActualizarProductos();
            for (var ca : lc.categorias){
                dfm.addElement(ca.nom);
            }
            ListCategorias.setModel(dfm);
        } catch (SQLException ex) {
            Logger.getLogger(GestionWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formComponentShown

    private void bActUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActUsuActionPerformed
        try {
            ListaUsu lu = c.ActualizarUsuario();
            DefaultTableModel dtm = new DefaultTableModel();
            dtm.addColumn("usuario");
            dtm.addColumn("nombre");
            dtm.addColumn("password");
            for (var u : lu.usuarios){
                dtm.addRow(new Object[]{u.getUsuario(), u.getNombre(), u.getPassword()});
            }
            
            tUsu.setModel(dtm);
        } catch (SQLException ex) {
            Logger.getLogger(GestionWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bActUsuActionPerformed

    private void bBorUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBorUsuActionPerformed
        
        try {
            int row = tUsu.getSelectedRow();
            Usuario us = new Usuario(tUsu.getValueAt(row, 0).toString(), tUsu.getValueAt(row, 1).toString(), tUsu.getValueAt(row, 2).toString());
            ListaUsu lu = c.BorrarUsuario(us);
            DefaultTableModel dtm = new DefaultTableModel();
            dtm.addColumn("usuario");
            dtm.addColumn("nombre");
            dtm.addColumn("password");
            cbEmpleado.removeAllItems();
            for (var u : lu.usuarios){
                dtm.addRow(new Object[]{u.getUsuario(), u.getNombre(), u.getPassword()});
                cbEmpleado.addItem(u.getNombre());
            }
            
            tUsu.setModel(dtm);
        } catch (SQLException ex) {
            Logger.getLogger(GestionWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bBorUsuActionPerformed

    private void bInsUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInsUsuActionPerformed
        try {
            Usuario us = new Usuario(txtUsu.getText(), txtNomUsu.getText(), new String(txtPass.getPassword()));
            ListaUsu lu = c.InsertarUsuario(us);
            DefaultTableModel dtm = new DefaultTableModel();
            dtm.addColumn("usuario");
            dtm.addColumn("nombre");
            dtm.addColumn("password");
            cbEmpleado.removeAllItems();
            for (var u : lu.usuarios){
                dtm.addRow(new Object[]{u.getUsuario(), u.getNombre(), u.getPassword()});
                cbEmpleado.addItem(u.getNombre());
            }
            
            tUsu.setModel(dtm);
            txtUsu.setEnabled(false);
            txtNomUsu.setEnabled(false);
            txtPass.setEnabled(false);
        } catch (SQLException ex) {
            Logger.getLogger(GestionWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bInsUsuActionPerformed

    private void bEdUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEdUsuActionPerformed
        txtUsu.setEnabled(true);
        txtNomUsu.setEnabled(true);
        txtPass.setEnabled(true);
        
        
        txtUsu.setText("");
        txtNomUsu.setText("");
        txtPass.setText("");
    }//GEN-LAST:event_bEdUsuActionPerformed

    private void BelimProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BelimProdActionPerformed
        try {    
            int i;
            if ((i = tProd.getSelectedRow()) != -1){
            
                Producto p = new Producto(tProd.getValueAt(i, 0).toString(), tProd.getValueAt(i, 1).toString(), tProd.getValueAt(i, 2).toString(), Double.parseDouble(tProd.getValueAt(i, 4).toString()), tProd.getValueAt(i, 3).toString());
                ListaProd lp = c.BorrarProducto(p);
                DefaultTableModel dfm = new DefaultTableModel();
                
                dfm.addColumn("id");
                dfm.addColumn("nombre");
                dfm.addColumn("categoria");
                dfm.addColumn("info");
                dfm.addColumn("precio");
                for (var ca : lp.lp){
                    dfm.addRow(new Object[] {ca.getId(), ca.getNombre(), ca.getCategoria(), ca.getInfo(), ca.getPrecio()});
                }
                tProd.setModel(dfm);
            
            }
        } catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
    }//GEN-LAST:event_BelimProdActionPerformed

    private void bPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPagarActionPerformed
        try{
            c.Pagar(idCom);
        } catch (SQLException ex) {
            Logger.getLogger(GestionWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bPagarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionWindow().setVisible(true);
            }
        });
    }

    public void RellenarComanda(ProductosComanda pc){
        if (idCom > 0){
            lblComanda.setText("Comanda: " + idCom);
        }else{
            lblComanda.setText("Comanda: ");
        }
    
        cbEmpleado.setSelectedItem(empleado);
            
        
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.addColumn("Id Producto");
        dtm.addColumn("Nombre Producto");
        dtm.addColumn("Precio");
        for (var p : pc.listaProd){
            dtm.addRow(new Object[]{p.getId(), p.getNom(), p.getPrec()});
        }
        comanda.setModel(dtm);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BInsProd;
    private javax.swing.JButton BactCat;
    private javax.swing.JButton BactProd;
    private javax.swing.JButton BelimCat;
    private javax.swing.JButton BelimProd;
    private javax.swing.JButton BinsCat;
    private javax.swing.JComboBox<String> CbCategorias;
    private javax.swing.JTextArea InfoProd;
    private javax.swing.JLabel LblMesa;
    private javax.swing.JList<String> ListCategorias;
    private javax.swing.JTextField TxtCodCat;
    private javax.swing.JTextField TxtCodProd;
    private javax.swing.JTextField TxtNomCat;
    private javax.swing.JTextField TxtNomProd;
    private javax.swing.JTextField TxtPrecio;
    private javax.swing.JButton b1;
    private javax.swing.JButton b10;
    private javax.swing.JButton b11;
    private javax.swing.JButton b12;
    private javax.swing.JButton b13;
    private javax.swing.JButton b14;
    private javax.swing.JButton b15;
    private javax.swing.JButton b16;
    private javax.swing.JButton b17;
    private javax.swing.JButton b18;
    private javax.swing.JButton b19;
    private javax.swing.JButton b2;
    private javax.swing.JButton b20;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JButton bActUsu;
    private javax.swing.JButton bAumentar;
    private javax.swing.JButton bBorUsu;
    private javax.swing.JButton bDisminuir;
    private javax.swing.JButton bEdUsu;
    private javax.swing.JButton bElegirMesa;
    private javax.swing.JButton bIniciar;
    private javax.swing.JButton bInsUsu;
    private javax.swing.JButton bInsertarProdC;
    private javax.swing.JButton bPagar;
    private javax.swing.JButton bQuitarProdC;
    private javax.swing.JComboBox<String> cbEmpleado;
    private javax.swing.JTable comanda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JLabel lblComanda;
    private javax.swing.JList<String> listProd;
    private javax.swing.JList<String> listaGCat;
    private javax.swing.JPanel panelComandas;
    private javax.swing.JPanel panelGestionUsu;
    private javax.swing.JPanel panelProductos;
    private javax.swing.JTable tProd;
    private javax.swing.JTable tUsu;
    private javax.swing.JTextArea txtInfoProd;
    private javax.swing.JTextField txtNomUsu;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUsu;
    private javax.swing.JTabbedPane ventanas;
    // End of variables declaration//GEN-END:variables

}
